extends Node
## Cross-scene lifecycle events. Scene-local telemetry uses direct signals.

signal race_countdown_changed(value: int)
signal race_started()
signal checkpoint_passed(index: int, total: int, split_usec: int)
signal race_finished(time_usec: int, medal: StringName, is_new_best: bool)
signal race_results_ready(result: Dictionary)
signal race_reset()
signal game_paused(paused: bool)
signal activity_prepared(activity: StringName)
signal activity_started(activity: StringName)
signal activity_attempt_started(context: Dictionary)
signal freestyle_score_changed(score: int, combo: int, last_points: int)
signal freestyle_trick_scored(result: Dictionary)
signal discovery_progress_changed(current: int, total: int)
signal activity_completed(summary: Dictionary)
signal interface_feedback_requested(kind: StringName, context: StringName)
signal rider_voice_preview_requested(voice_id: StringName)
signal audio_caption_requested(source: StringName, text: String, priority: int)
