extends Node3D
class_name TrackEvolution
## Session-local route wear generated by real player and opponent traffic.
##
## The system deliberately leaves authoritative collision geometry unchanged.
## It turns repeated passages into one low-cost visual mesh and a bounded
## handling context, so an evolving line is readable and useful without
## producing unpredictable bumps, shortcuts, or frame-rate-dependent physics.

const LANE_COUNT := 5
const BIN_LENGTH_METERS := 12.0
const PASS_WEAR_PLAYER := 0.105
const PASS_WEAR_OPPONENT := 0.075
const ADJACENT_WEAR_RATIO := 0.22
const MAX_WEAR := 0.85
const VISUAL_THRESHOLD := 0.10
const VISUAL_REFRESH_SECONDS := 0.35

var _active := false
var _track_id: StringName = &""
var _surface: StringName = &"PACKED"
var _weather: StringName = &"CLEAR"
var _route := PackedVector3Array()
var _cumulative := PackedFloat32Array()
var _route_length := 0.0
var _track_half_width := 5.0
var _wear: Array[PackedFloat32Array] = []
var _last_bin_by_rider: Dictionary = {}
var _sampled_passes := 0
var _visual_refresh_remaining := 0.0
var _visual_dirty := false
var _visible_grooves := 0
var _maximum_wear := 0.0
var _player_line_snapshot: Dictionary = {}
var _mesh_instance: MeshInstance3D
var _mesh: ImmediateMesh
var _material: StandardMaterial3D


func _ready() -> void:
	_ensure_visual()


func configure(
	route: PackedVector3Array,
	track_width: float,
	track_id: StringName,
	weather: StringName,
	surface: StringName,
	enabled: bool = true
) -> void:
	_track_id = track_id
	_route = route.duplicate()
	_track_half_width = maxf(track_width * 0.5, 2.0)
	_build_cumulative_distances()
	_active = enabled and _route.size() >= 2 and _route_length >= BIN_LENGTH_METERS
	set_surface(surface, weather)
	reset_evolution()
	visible = _active


func set_surface(surface: StringName, weather: StringName = &"") -> void:
	_surface = surface if not surface.is_empty() else &"PACKED"
	if not weather.is_empty():
		_weather = weather
	_update_material()
	if not _player_line_snapshot.is_empty():
		var chainage := float(_player_line_snapshot.get(&"chainage", 0.0))
		var lateral := float(_player_line_snapshot.get(&"signed_lateral", 0.0))
		_player_line_snapshot = sample_line(chainage, lateral, false)


func reset_evolution() -> void:
	_wear.clear()
	var bin_count := maxi(ceili(_route_length / BIN_LENGTH_METERS), 1) if _active else 0
	for _bin_index: int in bin_count:
		var lanes := PackedFloat32Array()
		lanes.resize(LANE_COUNT)
		lanes.fill(0.0)
		_wear.append(lanes)
	_last_bin_by_rider.clear()
	_sampled_passes = 0
	_visible_grooves = 0
	_maximum_wear = 0.0
	_player_line_snapshot = _empty_line_snapshot()
	_visual_refresh_remaining = 0.0
	_visual_dirty = true
	_rebuild_visual()


func clear_evolution() -> void:
	_active = false
	_track_id = &""
	_route = PackedVector3Array()
	_cumulative = PackedFloat32Array()
	_route_length = 0.0
	_wear.clear()
	_last_bin_by_rider.clear()
	_player_line_snapshot = _empty_line_snapshot()
	_visible_grooves = 0
	_maximum_wear = 0.0
	_sampled_passes = 0
	_visual_dirty = true
	_rebuild_visual()
	visible = false


func advance(
	delta: float,
	player_sample: Dictionary,
	opponent_samples: Array[Dictionary]
) -> void:
	if not _active:
		return
	var player_line_id := StringName(player_sample.get(&"route_line_id", &"MAIN"))
	if player_line_id == &"MAIN":
		record_pass(
			&"PLAYER",
			float(player_sample.get(&"chainage", 0.0)),
			float(player_sample.get(&"signed_lateral", 0.0)),
			float(player_sample.get(&"speed_mps", 0.0)),
			true
		)
	for opponent: Dictionary in opponent_samples:
		if StringName(opponent.get(&"status", &"RUNNING")) != &"RUNNING":
			continue
		record_pass(
			StringName(opponent.get(&"rider_id", &"NPC")),
			float(opponent.get(&"progress", 0.0)),
			float(opponent.get(&"lane", 0.0)),
			float(opponent.get(&"speed_mps", 0.0)),
			false
		)
	_visual_refresh_remaining -= maxf(delta, 0.0)
	if _visual_dirty and _visual_refresh_remaining <= 0.0:
		_rebuild_visual()
		_visual_refresh_remaining = VISUAL_REFRESH_SECONDS


func record_pass(
	rider_id: StringName,
	chainage: float,
	signed_lateral: float,
	speed_mps: float,
	is_player: bool
) -> bool:
	if not _active or _wear.is_empty() or speed_mps < 2.5:
		return false
	var safe_chainage := _normalized_chainage(chainage)
	var bin_index := clampi(
		floori(safe_chainage / BIN_LENGTH_METERS),
		0,
		_wear.size() - 1
	)
	var rider_key := String(rider_id)
	if int(_last_bin_by_rider.get(rider_key, -1)) == bin_index:
		return false
	_last_bin_by_rider[rider_key] = bin_index
	var lane_index := _nearest_lane_index(signed_lateral)
	var speed_factor := clampf(speed_mps / 12.0, 0.65, 1.20)
	var base_wear := (
		PASS_WEAR_PLAYER if is_player else PASS_WEAR_OPPONENT
	) * speed_factor * _erodibility()
	_add_wear(bin_index, lane_index, base_wear)
	if lane_index > 0:
		_add_wear(bin_index, lane_index - 1, base_wear * ADJACENT_WEAR_RATIO)
	if lane_index + 1 < LANE_COUNT:
		_add_wear(bin_index, lane_index + 1, base_wear * ADJACENT_WEAR_RATIO)
	_sampled_passes += 1
	_visual_dirty = true
	return true


func sample_line(
	chainage: float,
	signed_lateral: float,
	remember_player: bool = true
) -> Dictionary:
	if not _active or _wear.is_empty():
		return _empty_line_snapshot()
	var safe_chainage := _normalized_chainage(chainage)
	var bin_index := clampi(
		floori(safe_chainage / BIN_LENGTH_METERS),
		0,
		_wear.size() - 1
	)
	var lane_index := _nearest_lane_index(signed_lateral)
	var wear := clampf(_wear[bin_index][lane_index], 0.0, MAX_WEAR)
	var wet := _is_wet_policy()
	var state := &"FRESH"
	if wear >= 0.62:
		state = &"DEEP_RUT"
	elif wear >= 0.30:
		state = &"SLICK_GROOVE" if wet else &"COMPACTED"
	elif wear >= VISUAL_THRESHOLD:
		state = &"FORMING"
	var grip_multiplier := (
		1.0 - wear * 0.045 if wet else 1.0 + wear * 0.055
	)
	var drive_multiplier := (
		1.0 - wear * 0.018 if wet else 1.0 + wear * 0.025
	)
	var snapshot := {
		&"active": true,
		&"state": state,
		&"chainage": safe_chainage,
		&"signed_lateral": signed_lateral,
		&"bin_index": bin_index,
		&"lane_index": lane_index,
		&"lane_center": _lane_center(lane_index),
		&"wear": wear,
		&"grip_multiplier": clampf(grip_multiplier, 0.96, 1.05),
		&"drive_multiplier": clampf(drive_multiplier, 0.98, 1.025),
		&"rut_strength": smoothstep(0.18, 0.72, wear) * 0.72,
		&"wet_policy": wet,
	}
	if remember_player:
		_player_line_snapshot = snapshot.duplicate(true)
	return snapshot


func force_refresh_visual() -> void:
	_rebuild_visual()
	_visual_refresh_remaining = VISUAL_REFRESH_SECONDS


func get_snapshot() -> Dictionary:
	return {
		&"active": _active,
		&"track_id": _track_id if _active else &"",
		&"surface": _surface if _active else &"",
		&"weather": _weather if _active else &"",
		&"route_length": _route_length if _active else 0.0,
		&"bin_count": _wear.size() if _active else 0,
		&"lane_count": LANE_COUNT if _active else 0,
		&"sampled_passes": _sampled_passes if _active else 0,
		&"visible_grooves": _visible_grooves if _active else 0,
		&"maximum_wear": _maximum_wear if _active else 0.0,
		&"collision_count": 0,
		&"player_line": (
			_player_line_snapshot.duplicate(true)
			if _active else _empty_line_snapshot()
		),
	}


func _add_wear(bin_index: int, lane_index: int, amount: float) -> void:
	var lanes := _wear[bin_index]
	lanes[lane_index] = minf(lanes[lane_index] + maxf(amount, 0.0), MAX_WEAR)
	_maximum_wear = maxf(_maximum_wear, lanes[lane_index])
	_wear[bin_index] = lanes


func _nearest_lane_index(signed_lateral: float) -> int:
	var result := 0
	var nearest_distance := INF
	for lane_index: int in LANE_COUNT:
		var distance := absf(signed_lateral - _lane_center(lane_index))
		if distance < nearest_distance:
			nearest_distance = distance
			result = lane_index
	return result


func _lane_center(lane_index: int) -> float:
	var normalized := (float(lane_index) / float(LANE_COUNT - 1)) * 2.0 - 1.0
	return normalized * _track_half_width * 0.68


func _erodibility() -> float:
	if _surface in [&"MUD", &"LOOSE", &"LOOSE_DIRT", &"RUTTED", &"SAND"]:
		return 1.18
	if _surface in [&"ROCK", &"HARDPACK"]:
		return 0.72
	return 1.0


func _is_wet_policy() -> bool:
	return (
		_surface in [&"WET", &"MUD"]
		or _weather in [&"RAIN", &"STORM", &"WET"]
	)


func _normalized_chainage(chainage: float) -> float:
	if _route_length <= 0.001:
		return 0.0
	if chainage > _route_length or chainage < 0.0:
		return fposmod(chainage, _route_length)
	return clampf(chainage, 0.0, maxf(_route_length - 0.001, 0.0))


func _build_cumulative_distances() -> void:
	_cumulative = PackedFloat32Array()
	_cumulative.resize(_route.size())
	_route_length = 0.0
	if _route.is_empty():
		return
	_cumulative[0] = 0.0
	for index: int in range(1, _route.size()):
		_route_length += _route[index - 1].distance_to(_route[index])
		_cumulative[index] = _route_length


func _sample_route(chainage: float) -> Vector3:
	if _route.is_empty():
		return Vector3.ZERO
	if _route.size() == 1 or _route_length <= 0.001:
		return _route[0]
	var target := clampf(chainage, 0.0, _route_length)
	var low := 0
	var high := _cumulative.size() - 1
	while low + 1 < high:
		var middle := (low + high) / 2
		if float(_cumulative[middle]) <= target:
			low = middle
		else:
			high = middle
	var segment := clampi(low, 0, _route.size() - 2)
	var start_distance := float(_cumulative[segment])
	var end_distance := float(_cumulative[segment + 1])
	var ratio := (
		clampf((target - start_distance) / (end_distance - start_distance), 0.0, 1.0)
		if end_distance - start_distance > 0.0001 else 0.0
	)
	return _route[segment].lerp(_route[segment + 1], ratio)


func _ensure_visual() -> void:
	if is_instance_valid(_mesh_instance):
		return
	_mesh = ImmediateMesh.new()
	_mesh_instance = MeshInstance3D.new()
	_mesh_instance.name = "EvolvingGrooves"
	_mesh_instance.mesh = _mesh
	_mesh_instance.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	add_child(_mesh_instance)
	_update_material()


func _update_material() -> void:
	if _material == null:
		_material = StandardMaterial3D.new()
		_material.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
		_material.vertex_color_use_as_albedo = true
		_material.vertex_color_is_srgb = true
		_material.roughness = 0.96
		_material.metallic = 0.0
		_material.cull_mode = BaseMaterial3D.CULL_DISABLED
	_material.albedo_color = (
		Color(0.23, 0.17, 0.12, 1.0)
		if _is_wet_policy()
		else Color(0.34, 0.20, 0.10, 1.0)
	)


func _rebuild_visual() -> void:
	_ensure_visual()
	_mesh.clear_surfaces()
	_visible_grooves = 0
	if not _active or _wear.is_empty():
		_visual_dirty = false
		return
	var surface_started := false
	for bin_index: int in _wear.size():
		var lanes := _wear[bin_index]
		for lane_index: int in LANE_COUNT:
			var wear := clampf(lanes[lane_index], 0.0, MAX_WEAR)
			if wear < VISUAL_THRESHOLD:
				continue
			if not surface_started:
				_mesh.surface_begin(Mesh.PRIMITIVE_TRIANGLES, _material)
				surface_started = true
			_add_groove_quad(bin_index, lane_index, wear)
			_visible_grooves += 1
	if surface_started:
		_mesh.surface_end()
	_visual_dirty = false


func _add_groove_quad(bin_index: int, lane_index: int, wear: float) -> void:
	var start_chain := float(bin_index) * BIN_LENGTH_METERS + 0.35
	var end_chain := minf(
		float(bin_index + 1) * BIN_LENGTH_METERS - 0.35,
		_route_length
	)
	if end_chain - start_chain < 0.4:
		return
	var start := _sample_route(start_chain)
	var end := _sample_route(end_chain)
	var tangent := (end - start).normalized()
	var right := tangent.cross(Vector3.UP).normalized()
	if right.length_squared() < 0.5:
		right = Vector3.RIGHT
	var normal := right.cross(tangent).normalized()
	if normal.dot(Vector3.UP) < 0.0:
		normal = -normal
	var lane_center := _lane_center(lane_index)
	var width := lerpf(0.15, 0.42, wear / MAX_WEAR)
	var lift := lerpf(0.035, 0.018, wear / MAX_WEAR)
	var start_center := start + right * lane_center + normal * lift
	var end_center := end + right * lane_center + normal * lift
	var color := (
		Color(0.12, 0.105, 0.085, lerpf(0.28, 0.78, wear / MAX_WEAR))
		if _is_wet_policy()
		else Color(0.24, 0.105, 0.035, lerpf(0.24, 0.70, wear / MAX_WEAR))
	)
	var a := start_center - right * width
	var b := start_center + right * width
	var c := end_center + right * width
	var d := end_center - right * width
	_add_visual_triangle(a, b, c, normal, color)
	_add_visual_triangle(a, c, d, normal, color)


func _add_visual_triangle(
	a: Vector3,
	b: Vector3,
	c: Vector3,
	normal: Vector3,
	color: Color
) -> void:
	for vertex: Vector3 in [a, b, c]:
		_mesh.surface_set_normal(normal)
		_mesh.surface_set_color(color)
		_mesh.surface_add_vertex(vertex)


func _empty_line_snapshot() -> Dictionary:
	return {
		&"active": false,
		&"state": &"FRESH",
		&"chainage": 0.0,
		&"signed_lateral": 0.0,
		&"bin_index": 0,
		&"lane_index": 0,
		&"lane_center": 0.0,
		&"wear": 0.0,
		&"grip_multiplier": 1.0,
		&"drive_multiplier": 1.0,
		&"rut_strength": 0.0,
		&"wet_policy": false,
	}
